(async () => {
    console.log(`Hello,World!`);
})().catch((err) => {
    console.error(err);
});
